### ISSUE TITLE
Styling left gutter

### ISSUE THREAD

**Issue by bronze** [amp343/monokai-shade#2]
Hi there

Mind telling me what you used to style the left gutter on the screenshot as yellow?

cheers

**Comment by amp343** [comment]
That styling comes in from https://atom.io/packages/git-diff, a core Atom package. Marking which lines have been changed (yellow), deleted (red) or added (green)

**Comment by amp343** [comment]
To be specific, that plugin adds the colored border like:

<img width="323" alt="screen shot 2015-07-11 at 3 36 11 pm" src="https://cloud.githubusercontent.com/assets/425365/8635099/a929e81c-27e2-11e5-9c24-820fa04a56ac.png">

**Comment by bronze** [comment]
thx!
