### ISSUE TITLE
Font always set to Menlo.

### ISSUE THREAD

**Issue by mdsitton** [amp343/monokai-shade#3]
This overwrites the users font, and on a platform that doesnt have it the font becomes some nonmonospaced font.

**Comment by amp343** [comment]
No Menlo... a PC user?? :smiley: 

Given that there does not appear to be any super convenient way to allow the user font to fall through to the syntax theme at this point (https://github.com/atom/atom/issues/5355), I merged a PR in that at least provides some good, serviceable fallback fonts.

`v3.0.4` now available via APM.

**Comment by mdsitton** [comment]
Well I use windows, linux, and OS X, i had installed the theme on my windows pc and things were a bit borked lol
