### ISSUE TITLE
The latest release tag isn't setup as a release in github.

### ISSUE THREAD

**Issue by mdsitton** [amp343/monokai-shade#5]
I think this is causing the newer releases to not be available from within atom. (the menlo issue is still persistant with the version installed)

**Comment by mdsitton** [comment]
The reason i gave isnt true exactly it seems, but the issue still stands. The monokai-shade-src package seems to work fine..

**Comment by amp343** [comment]
Ah, good call. The `name` in `package.json` got changed to the wrong thing.
Didn't notice that on the diff! Will have to swap it back to point to the
right one.

**Comment by amp343** [comment]
package name corrected: 11a165708fb684e6c1c5b7f2767d87c3748f94cf

version is now `0.3.5`
